RUN_FULL_EXPERIMENT = True
FOCUS_ON_KASHIN = True
RUN_LOWBIT_EXPERIMENT = True
FIXED_BITS = 2
FIXED_K_LEVELS = 4
NUM_ROUNDS_FOCUS = 50
TRADEOFF_BITS = [1, 2, 4]
TRADEOFF_ROUNDS = 8
DEBUG_RANGE = True
RUN_DISTRIBUTION_TEST = False
RUN_LLOYD_MAX_TEST = False
KASHIN_REDUNDANCY_SETTINGS = [1.10, 1.25, 1.50, 2.00]
KASHIN_LAMBDA = 2.0
MODEL_SEED = 42
EXPERIMENT_SEED = 2026
NUM_CLIENTS = 10
IMAGES_PER_CLIENT = 600
# Fewer clients make compression noise less diluted by client averaging.
# NUM_CLIENTS=10 remains the main baseline; this is the tradeoff sensitivity run.
LOWBIT_NUM_CLIENTS = 3
LOWBIT_IMAGES_PER_CLIENT = 600
CRN_PAIRED = True

